# Generated by Django 3.0.6 on 2020-05-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usrmodel',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='usrmodel',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usrmodel',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
