# Generated by Django 3.0.6 on 2020-05-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0002_auto_20200518_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usrmodel',
            name='bio',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
