# Generated by Django 3.0.6 on 2020-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microapp', '0003_auto_20200518_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usrmodel',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='usrmodel',
            name='location',
        ),
        migrations.AddField(
            model_name='usrmodel',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usrmodel',
            name='url',
            field=models.URLField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='usrmodel',
            name='bio',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
